aligner:
 _target_: preprocessing.aligner.Aligner
 yolo_model: C:\Users\user\Desktop\projects\recognition_model\weights\yolo.pt
 dlib_model: C:\Users\user\Desktop\projects\recognition_model\weights\dlib_predictor.dat
rec_path: C:\Users\user\Desktop\tempo\faces_webface_112x112\faces_webface_112x112\train.rec
idx_path: C:\Users\user\Desktop\tempo\faces_webface_112x112\faces_webface_112x112\train.idx
save_path: C:\Users\user\Desktop\projects\recognition_model\processed_images