defaults:
  - _self_
  - model: model
  - opt: adam
  - scheduler: onecyclelr
  - loss: arcface
  - train_dataset: dataset
  - val_dataset: dataset

training:
  epochs: 50
  batch_size: 128
  save_path: 'recognition_model/saved_models'